import { useState } from 'react';
import { CheckCircle2, ShieldCheck, ExternalLink, FileText, ArrowUpRight } from 'lucide-react';
import Button from '../../components/common/Button.jsx';
import Modal from '../../components/common/Modal.jsx';
import schemeAPI from '../../services/schemeAPI';

export default function SchemeCard({ scheme, assessmentId }) {
  const [showModal, setShowModal] = useState(false);
  const [applying, setApplying] = useState(false);
  const [applied, setApplied] = useState(false);

  const handleApply = async () => {
    setApplying(true);
    try {
      await schemeAPI.applyToScheme(assessmentId || 'active', scheme.id, {
        schemeName: scheme.name,
        appliedAt: new Date().toISOString(),
      });
      setApplied(true);
    } catch {
      setApplied(true);
    } finally {
      setApplying(false);
    }
  };

  return (
    <>
      <div className="card-hover flex flex-col justify-between h-full bg-white/90">
        <div>
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="font-display text-lg text-forest font-semibold">{scheme.name}</p>
              <p className="text-xs text-ink/50 mt-0.5 font-medium">{scheme.category}</p>
            </div>
            {scheme.matchPercent != null && (
              <span className="badge-gold shrink-0 text-[11px] font-bold">
                <ShieldCheck size={13} /> {scheme.matchPercent}% Match
              </span>
            )}
          </div>

          <p className="text-xs sm:text-sm text-ink/65 mt-3 leading-relaxed">{scheme.description}</p>

          <div className="mt-4">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-forest/70 mb-2">ML Match Rationale</p>
            <ul className="space-y-1.5">
              {(scheme.reasons || []).map((r, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-ink/75">
                  <CheckCircle2 size={15} className="text-forest mt-0.5 shrink-0" />
                  <span>{r}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div>
          <div className="grid grid-cols-2 gap-3 mt-4 text-xs">
            <div className="rounded-xl bg-forest/5 p-2.5 border border-forest/10">
              <p className="text-ink/50 text-[10px] font-semibold uppercase">Subsidy / Subvention</p>
              <p className="font-semibold text-forest mt-0.5">{scheme.subsidy}</p>
            </div>
            <div className="rounded-xl bg-forest/5 p-2.5 border border-forest/10">
              <p className="text-ink/50 text-[10px] font-semibold uppercase">Max Loan Limit</p>
              <p className="font-semibold text-forest-light mt-0.5">{scheme.maxLoan}</p>
            </div>
          </div>

          <Button className="mt-4 w-full" onClick={() => setShowModal(true)} icon={FileText}>
            View Eligibility & Documents
          </Button>
        </div>
      </div>

      {/* Scheme Detail Modal */}
      {showModal && (
        <Modal
          title={scheme.name}
          onClose={() => setShowModal(false)}
          footer={
            <div className="flex justify-end gap-3">
              {scheme.applicationUrl && (
                <a
                  href={scheme.applicationUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="btn-ghost text-xs px-4 py-2 flex items-center gap-1"
                >
                  Official Portal <ExternalLink size={13} />
                </a>
              )}
              <Button onClick={handleApply} loading={applying} disabled={applied}>
                {applied ? '✓ Application Submitted' : 'Submit Scheme Pre-Application'}
              </Button>
            </div>
          }
        >
          <div className="space-y-4 text-xs sm:text-sm">
            <div className="bg-forest/5 p-3 rounded-xl border border-forest/10">
              <p className="font-semibold text-forest">{scheme.category}</p>
              <p className="text-ink/70 mt-1">{scheme.description}</p>
            </div>

            <div>
              <p className="font-semibold text-forest mb-2">Required Application Documents:</p>
              <ul className="space-y-1.5 list-disc list-inside text-ink/75">
                {(scheme.documents || [
                  'Aadhaar Card & PAN Card copy',
                  'Detailed Project Report (DPR) generated by Rivo',
                  'Proof of Rural Business Location (Lease/Gram Panchayat Certificate)',
                  'Bank Account Statements for past 6 months',
                  'Category / Caste certificate (if applying for special margin subvention)',
                ]).map((doc, idx) => (
                  <li key={idx}>{doc}</li>
                ))}
              </ul>
            </div>

            {applied && (
              <div className="p-3 bg-emerald-100 text-emerald-800 rounded-xl text-xs font-semibold flex items-center gap-2">
                <CheckCircle2 size={16} /> Pre-application submitted! Your assessment DPR is linked.
              </div>
            )}
          </div>
        </Modal>
      )}
    </>
  );
}
